package com.dd3boh.outertune.models.metadata

import com.zionhuang.innertube.models.*
import org.junit.Assert.*
import org.junit.Test

class ArtTrackOriginalNamesTest {
    private val id = "abcdefghijk"
    private val song = SongItem(id, "Some Original Title", listOf(Artist("Artist · Name", "UCartist")),
        Album("Original Album", "MPREalbum"), thumbnail = "", endpoint = WatchEndpoint(videoId = id,
            watchEndpointMusicSupportedConfigs = WatchEndpoint.WatchEndpointMusicSupportedConfigs(
                WatchEndpoint.WatchEndpointMusicSupportedConfigs.WatchEndpointMusicConfig("MUSIC_VIDEO_TYPE_ATV"))))
    private fun original(title: String = song.title, credit: String = "Artist · Name", album: String = "Original Album") =
        ArtTrackOriginalMetadata(id, title, "Wrong Topic Author", "UCdifferent",
            "Provided to YouTube by Example\n\n$title · $credit\n\n$album\n\nAuto-generated by YouTube.")

    @Test fun originalsUseKnownIdentitiesAndDoNotSplitLiteralArtistNames() {
        val names = artTrackOriginalNames(original(), song)
        assertEquals(3, names.size)
        assertEquals(listOf("UCartist"), names.filter { it.target.kind == OriginalNameKind.ARTIST }.map { it.target.id })
        assertEquals("Artist · Name", names.single { it.target.kind == OriginalNameKind.ARTIST }.name)
    }

    @Test fun unknownCreditAndDifferentAlbumDoNotBorrowAnIdOrTopicAuthor() {
        val names = artTrackOriginalNames(original(credit = "Someone Else", album = "Another Edition"), song)
        assertEquals(listOf(OriginalNameKind.SONG), names.map { it.target.kind })
    }

    @Test fun missingArtistIdOrUnstructuredDescriptionRetainsOnlySafeNames() {
        val unresolved = song.copy(artists = listOf(Artist("Artist · Name", null)))
        assertFalse(artTrackOriginalNames(original(), unresolved).any { it.target.kind == OriginalNameKind.ARTIST })
        assertEquals(1, artTrackOriginalNames(original().copy(shortDescription = "Fan description"), song).size)
    }

    @Test fun unrelatedVideoAndMusicVideoAreNotOriginalArtTrackEvidence() {
        assertTrue(artTrackOriginalNames(original().copy(videoId = "wrong_video"), song).isEmpty())
        assertTrue(artTrackOriginalNames(original(), song.copy(endpoint = null)).isEmpty())
    }

    @Test fun japaneseOriginalIsKeptEvenIfTheEnglishApiSuppliesRomanization() {
        val names = artTrackOriginalNames(original(title = "夜に駆ける"), song.copy(title = "Yoru ni Kakeru"))
        assertEquals("夜に駆ける", names.first().name)
    }

    @Test fun inconsistentDescriptionTitleCannotSupplyAlbumLanguageContext() {
        val mismatched = original().copy(shortDescription = original().shortDescription!!
            .replace("Some Original Title · ", "Different Title · "))
        val names = artTrackOriginalNames(mismatched, song)

        assertEquals(listOf(OriginalNameKind.SONG), names.map { it.target.kind })
        assertNull(names.single().albumId)
    }

    @Test fun aTruncatedDescriptionCannotReuseItsFooterAsAnAlbum() {
        val footer = "Auto-generated by YouTube."
        val truncated = original().copy(shortDescription =
            "Provided to YouTube by Example\n\n${song.title} · Artist · Name\n\n$footer")

        val names = artTrackOriginalNames(truncated, song.copy(album = Album(footer, "MPREalbum")))
        assertEquals(listOf(OriginalNameKind.SONG), names.map { it.target.kind })
        assertNull(names.single().albumId)
    }

    @Test fun restrictedAlbumTrackCanUseItsExactStructuredMainMetadataWithoutAWatchEndpoint() {
        val albumSong = song.copy(endpoint = null, isPlayable = false)
        val names = albumTrackOriginalNames(original(), albumSong)

        assertEquals(listOf(OriginalNameKind.SONG, OriginalNameKind.ARTIST, OriginalNameKind.ALBUM), names.map { it.target.kind })
        assertEquals(song.title, names.first().name)
        assertEquals("UCartist", names[1].target.id)
        assertEquals("Artist · Name", names[1].name)
        assertTrue(names.all { it.sourceVideoId == id && it.albumId == "MPREalbum" })
        assertTrue(artTrackOriginalNames(original(), albumSong).isEmpty())
        assertEquals(names, albumTrackOriginalNames(original(), song))
    }

    @Test fun albumPathRejectsWrongVideoIdentityAndExplicitNonArtTracks() {
        assertTrue(albumTrackOriginalNames(original().copy(videoId = "12345678901"), song).isEmpty())
        assertTrue(albumTrackOriginalNames(original().copy(videoId = "invalid"), song.copy(id = "invalid")).isEmpty())
        assertTrue(albumTrackOriginalNames(original(), song.copy(endpoint = WatchEndpoint(videoId = "12345678901"))).isEmpty())
        for (videoType in listOf("MUSIC_VIDEO_TYPE_OMV", "MUSIC_VIDEO_TYPE_UGC")) {
            val endpoint = WatchEndpoint(videoId = id, watchEndpointMusicSupportedConfigs =
                WatchEndpoint.WatchEndpointMusicSupportedConfigs(
                    WatchEndpoint.WatchEndpointMusicSupportedConfigs.WatchEndpointMusicConfig(videoType)))
            assertTrue(albumTrackOriginalNames(original(), song.copy(endpoint = endpoint)).isEmpty())
        }
    }

    @Test fun albumPathRequiresAValidAlbumIdentityAndSingleLineDescriptionAlbum() {
        assertTrue(albumTrackOriginalNames(original(), song.copy(album = null)).isEmpty())
        for (albumId in listOf("", "MPRE", "MPREwrong id", "UCperson", "LB-local", "VLplaylist", "MPREalbum?other")) {
            assertTrue(albumTrackOriginalNames(original(), song.copy(album = Album("Original Album", albumId))).isEmpty())
        }
        assertTrue(albumTrackOriginalNames(original(), song.copy(album = Album("", "MPREalbum"))).isEmpty())
        assertTrue(albumTrackOriginalNames(original(album = ""), song).isEmpty())
        assertTrue(albumTrackOriginalNames(original(album = "Original Album\nAnother Edition"), song).isEmpty())
    }

    @Test fun albumEditionDifferenceKeepsItsDirectTrackMembershipWithoutAdoptingAnAlbumName() {
        val albumSong = song.copy(title = "Come Together (2019 Mix)", album = Album("Abbey Road (Super Deluxe Edition)", "MPREdeluxe"),
            endpoint = null, artists = emptyList())
        val names = albumTrackOriginalNames(original(title = albumSong.title, credit = "The Beatles", album = "Abbey Road"), albumSong)

        assertEquals(listOf(OriginalNameKind.SONG), names.map { it.target.kind })
        assertEquals("Come Together (2019 Mix)", names.single().name)
        assertEquals(id, names.single().target.id)
        assertEquals("MPREdeluxe", names.single().albumId)
    }

    @Test fun albumPathRejectsIncompleteOrInconsistentDistributorDescriptions() {
        val description = original().shortDescription!!
        val invalid = listOf(
            null,
            "Fan description",
            description.replace("Provided to YouTube by Example", "Provided to YouTube by "),
            description.replace("Provided to YouTube by Example", "Provided to YouTube by Example\nFan text"),
            description.replace("Provided to YouTube by Example", "Provided by Example"),
            description.replace("Auto-generated by YouTube.", "Uploaded by Artist"),
            description + "\nFan text",
            description.replace(song.title + " · ", "Different Title · "),
            description.replace("Artist · Name", ""),
            description.replace("Artist · Name", "Artist\nName"),
            "Provided to YouTube by Example\n\n${song.title} · Artist · Name\n\nAuto-generated by YouTube.",
        )
        invalid.forEach { text ->
            assertTrue("Description must be rejected: $text", albumTrackOriginalNames(original().copy(shortDescription = text), song).isEmpty())
        }
        assertTrue(albumTrackOriginalNames(original(title = ""), song).isEmpty())
        assertTrue(albumTrackOriginalNames(original(title = "Some\nOriginal Title"), song).isEmpty())
    }

    @Test fun albumPathDoesNotGuessArtistsFromDescriptionOrTopicAuthor() {
        val unresolved = song.copy(endpoint = null, artists = listOf(Artist("Artist · Name", null)))
        val expectedKinds = listOf(OriginalNameKind.SONG, OriginalNameKind.ALBUM)
        assertEquals(expectedKinds, albumTrackOriginalNames(original(), unresolved).map { it.target.kind })
        assertEquals(expectedKinds, albumTrackOriginalNames(original(), song.copy(artists = emptyList())).map { it.target.kind })
        assertEquals(expectedKinds, albumTrackOriginalNames(original(credit = "Someone Else"), song).map { it.target.kind })
        val partialCredit = song.copy(artists = listOf(Artist("Artist · Name", "UCartist"), Artist("Second Artist", "UCsecond")))
        assertEquals(expectedKinds, albumTrackOriginalNames(original(), partialCredit).map { it.target.kind })
    }

    @Test fun albumPathPreservesNonEnglishMainOriginalInsteadOfAnEnglishApiRomanization() {
        val names = albumTrackOriginalNames(original(title = "夜に駆ける"), song.copy(title = "Yoru ni Kakeru", endpoint = null))
        assertEquals("夜に駆ける", names.first().name)
        assertEquals(OriginalNameTarget(OriginalNameKind.SONG, id), names.first().target)
    }

    @Test fun albumPathAcceptsNormalWindowsLineEndingsWithoutRelaxingTextMatches() {
        val windowsDescription = original().copy(shortDescription = original().shortDescription!!.replace("\n", "\r\n"))
        assertEquals(albumTrackOriginalNames(original(), song), albumTrackOriginalNames(windowsDescription, song))
        assertFalse(albumTrackOriginalNames(original(album = "original album"), song).any { it.target.kind == OriginalNameKind.ALBUM })
    }

    @Test fun refreshedEditionKeepsOnlyEarlierNamesCorroboratedByTheSameSourceAgain() {
        val previous = albumTrackOriginalNames(original(), song)
        val secondEdition = song.copy(album = Album("Original Album (Deluxe)", "MPREdeluxe"))
        val incoming = albumTrackOriginalNames(original(), secondEdition)
        assertFalse(incoming.any { it.target.kind == OriginalNameKind.ALBUM })

        val retained = retainCorroboratedOriginalContext(original(), secondEdition, previous, incoming)

        assertEquals(previous.toSet(), retained.toSet())
        assertFalse(retained.any { it.target.id == "MPREdeluxe" })
    }

    @Test fun refreshedEditionCannotRetainAChangedAlbumArtistOrOriginalTitle() {
        val previous = albumTrackOriginalNames(original(), song)
        val secondEdition = song.copy(album = Album("Original Album (Deluxe)", "MPREdeluxe"))
        val changedAlbum = original(album = "Original Album (Deluxe)")
        val afterAlbumChange = retainCorroboratedOriginalContext(changedAlbum, secondEdition, previous,
            albumTrackOriginalNames(changedAlbum, secondEdition))
        assertEquals(listOf("MPREdeluxe"), afterAlbumChange.filter { it.target.kind == OriginalNameKind.ALBUM }.map { it.target.id })

        val changedArtistSong = secondEdition.copy(artists = listOf(Artist("Another Artist", "UCanother")))
        val changedArtist = original(credit = "Another Artist")
        val afterArtistChange = retainCorroboratedOriginalContext(changedArtist, changedArtistSong, previous,
            albumTrackOriginalNames(changedArtist, changedArtistSong))
        assertEquals(listOf("UCanother"), afterArtistChange.filter { it.target.kind == OriginalNameKind.ARTIST }.map { it.target.id })

        val changedTitle = original(title = "A Different Original Title")
        val afterTitleChange = retainCorroboratedOriginalContext(changedTitle, secondEdition, previous,
            albumTrackOriginalNames(changedTitle, secondEdition))
        assertFalse(afterTitleChange.any { it.target.kind == OriginalNameKind.ALBUM })
        assertEquals("MPREdeluxe", afterTitleChange.single { it.target.kind == OriginalNameKind.SONG }.albumId)
    }

    @Test fun incompleteNewObservationCannotReconstructRelatedNamesFromOldProof() {
        val previous = albumTrackOriginalNames(original(), song)
        val missingDescription = original().copy(shortDescription = null)
        assertTrue(retainCorroboratedOriginalContext(missingDescription, song, previous, emptyList()).isEmpty())
        val missingArtists = song.copy(artists = emptyList())
        val incoming = albumTrackOriginalNames(original(), missingArtists)
        val retained = retainCorroboratedOriginalContext(original(), missingArtists, previous, incoming)
        assertFalse(retained.any { it.target.kind == OriginalNameKind.ARTIST })
    }
}
