package com.dd3boh.outertune.models.metadata

import com.zionhuang.innertube.models.*
import org.junit.Assert.*
import org.junit.Test

class ArtTrackOriginalNamesTest {
    private val id = "abcdefghijk"
    private val song = SongItem(id, "Some Original Title", listOf(Artist("Artist · Name", "UCartist")),
        Album("Original Album", "MPREalbum"), thumbnail = "", endpoint = WatchEndpoint(videoId = id,
            watchEndpointMusicSupportedConfigs = WatchEndpoint.WatchEndpointMusicSupportedConfigs(
                WatchEndpoint.WatchEndpointMusicSupportedConfigs.WatchEndpointMusicConfig("MUSIC_VIDEO_TYPE_ATV"))))
    private fun original(title: String = song.title, credit: String = "Artist · Name", album: String = "Original Album") =
        ArtTrackOriginalMetadata(id, title, "Wrong Topic Author", "UCdifferent",
            "Provided to YouTube by Example\n\n$title · $credit\n\n$album\n\nAuto-generated by YouTube.")

    @Test fun originalsUseKnownIdentitiesAndDoNotSplitLiteralArtistNames() {
        val names = artTrackOriginalNames(original(), song)
        assertEquals(3, names.size)
        assertEquals(listOf("UCartist"), names.filter { it.target.kind == OriginalNameKind.ARTIST }.map { it.target.id })
        assertEquals("Artist · Name", names.single { it.target.kind == OriginalNameKind.ARTIST }.name)
    }

    @Test fun unknownCreditAndDifferentAlbumDoNotBorrowAnIdOrTopicAuthor() {
        val names = artTrackOriginalNames(original(credit = "Someone Else", album = "Another Edition"), song)
        assertEquals(listOf(OriginalNameKind.SONG), names.map { it.target.kind })
    }

    @Test fun missingArtistIdOrUnstructuredDescriptionRetainsOnlySafeNames() {
        val unresolved = song.copy(artists = listOf(Artist("Artist · Name", null)))
        assertFalse(artTrackOriginalNames(original(), unresolved).any { it.target.kind == OriginalNameKind.ARTIST })
        assertEquals(1, artTrackOriginalNames(original().copy(shortDescription = "Fan description"), song).size)
    }

    @Test fun unrelatedVideoAndMusicVideoAreNotOriginalArtTrackEvidence() {
        assertTrue(artTrackOriginalNames(original().copy(videoId = "wrong_video"), song).isEmpty())
        assertTrue(artTrackOriginalNames(original(), song.copy(endpoint = null)).isEmpty())
    }

    @Test fun japaneseOriginalIsKeptEvenIfTheEnglishApiSuppliesRomanization() {
        val names = artTrackOriginalNames(original(title = "夜に駆ける"), song.copy(title = "Yoru ni Kakeru"))
        assertEquals("夜に駆ける", names.first().name)
    }
}
