package com.dd3boh.outertune.models.metadata

import com.dd3boh.outertune.models.ArtistIdentity
import com.zionhuang.innertube.models.Album
import com.zionhuang.innertube.models.ArtTrackOriginalMetadata
import com.zionhuang.innertube.models.SongItem
import kotlinx.serialization.json.*

data class ArtTrackOriginalName(
    val target: OriginalNameTarget,
    val name: String,
    val sourceVideoId: String,
    val albumId: String? = null,
)

/**
 * Main's Art Track title/description carry distributor-supplied originals. The Music response
 * establishes identities; text only corroborates those existing links and never creates one.
 */
fun artTrackOriginalNames(original: ArtTrackOriginalMetadata, englishSong: SongItem): List<ArtTrackOriginalName> {
    if (original.videoId != englishSong.id || !Regex("[A-Za-z0-9_-]{11}").matches(original.videoId) ||
        original.title.isBlank() || original.title.any { it == '\n' || it == '\r' } ||
        englishSong.endpoint?.watchEndpointMusicSupportedConfigs?.watchEndpointMusicConfig?.musicVideoType != "MUSIC_VIDEO_TYPE_ATV") return emptyList()
    return buildList {
        val blocks = original.shortDescription.orEmpty().replace("\r\n", "\n").trim().split(Regex("\n\\s*\n"))
        val structured = blocks.size >= 4 && blocks.first().startsWith("Provided to YouTube by ") &&
            blocks.last() == "Auto-generated by YouTube."
        val matchingTitleCredit = structured && blocks[1].startsWith(original.title + " · ") &&
            !blocks[1].contains('\n')
        val album = englishSong.album?.takeIf {
            matchingTitleCredit && validOriginalAlbum(it) && blocks[2] == it.name && !blocks[2].contains('\n')
        }
        add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.SONG, original.videoId), original.title, original.videoId, album?.id))
        // Do not parse arbitrary descriptions, Topic channel authors, music cards or free-form bios.
        if (!structured) return@buildList
        val creditedArtists = englishSong.artistCredit?.artists ?: englishSong.artists
        val linked = creditedArtists.takeIf { it.isNotEmpty() && it.all { artist -> ArtistIdentity.onlineId(artist.id) != null } }
        // Compare the entire known credit. In particular, never split a name containing a delimiter.
        if (linked != null && blocks[1] == original.title + " · " + linked.joinToString(" · ") { it.name }) {
            linked.forEach { artist ->
                add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.ARTIST, ArtistIdentity.onlineId(artist.id)!!), artist.name, original.videoId, album?.id))
            }
        }
        album?.let {
            add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.ALBUM, it.id), it.name, original.videoId, it.id))
        }
    }
}

/**
 * Only call with a track returned directly by the requested, identity-checked English album page.
 * An old DB membership, a search result or a matching title cannot establish that provenance.
 * Restricted album tracks may omit their watch endpoint, so this path also requires Main's full
 * distributor description to corroborate the exact song. The page establishes album membership;
 * Main may name a different edition, which cannot supply a name for the page's album identity.
 */
fun albumTrackOriginalNames(original: ArtTrackOriginalMetadata, englishAlbumSong: SongItem): List<ArtTrackOriginalName> {
    if (original.videoId != englishAlbumSong.id || !Regex("[A-Za-z0-9_-]{11}").matches(original.videoId) ||
        original.title.isBlank() || original.title.any { it == '\n' || it == '\r' }) return emptyList()
    val endpoint = englishAlbumSong.endpoint
    if (endpoint?.videoId != null && endpoint.videoId != original.videoId) return emptyList()
    val videoType = endpoint?.watchEndpointMusicSupportedConfigs?.watchEndpointMusicConfig?.musicVideoType
    if (videoType != null && videoType != "MUSIC_VIDEO_TYPE_ATV") return emptyList()
    val album = englishAlbumSong.album?.takeIf(::validOriginalAlbum) ?: return emptyList()
    val blocks = original.shortDescription.orEmpty().replace("\r\n", "\n").trim().split(Regex("\n\\s*\n"))
    val providerPrefix = "Provided to YouTube by "
    if (blocks.size < 4 || !blocks.first().startsWith(providerPrefix) ||
        blocks.first().removePrefix(providerPrefix).isBlank() || blocks.first().contains('\n') ||
        blocks.first().contains('\r') || blocks.last() != "Auto-generated by YouTube.") return emptyList()
    val creditPrefix = original.title + " · "
    val creditLine = blocks[1]
    val describedAlbum = blocks[2]
    if (!creditLine.startsWith(creditPrefix) || creditLine.removePrefix(creditPrefix).isBlank() ||
        creditLine.any { it == '\n' || it == '\r' } || describedAlbum.isBlank() ||
        describedAlbum.any { it == '\n' || it == '\r' }) return emptyList()

    return buildList {
        add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.SONG, original.videoId), original.title, original.videoId, album.id))
        val creditedArtists = englishAlbumSong.artistCredit?.artists ?: englishAlbumSong.artists
        val linked = creditedArtists.takeIf { artists ->
            artists.isNotEmpty() && artists.all { artist ->
                ArtistIdentity.onlineId(artist.id) != null && artist.name.isNotBlank() &&
                    artist.name.none { it == '\n' || it == '\r' }
            }
        }
        // Main's author and description text never supply a missing artist identity.
        if (linked != null && creditLine == creditPrefix + linked.joinToString(" · ") { it.name }) {
            linked.forEach { artist ->
                add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.ARTIST, ArtistIdentity.onlineId(artist.id)!!),
                    artist.name, original.videoId, album.id))
            }
        }
        if (describedAlbum == album.name) {
            add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.ALBUM, album.id), album.name, original.videoId, album.id))
        }
    }
}

/**
 * Another edition can refresh an unchanged recording without withdrawing its earlier context.
 * Only retain a related name that this Main description corroborates again against identities
 * already established for the same source. A missing, changed or unrelated description cannot
 * supply an old album/artist name, and a different title starts a new source snapshot.
 */
fun retainCorroboratedOriginalContext(
    original: ArtTrackOriginalMetadata,
    englishSong: SongItem,
    previous: List<ArtTrackOriginalName>,
    incoming: List<ArtTrackOriginalName>,
): List<ArtTrackOriginalName> {
    val priorSource = previous.filter { it.sourceVideoId == original.videoId }
    val priorSong = priorSource.singleOrNull {
        it.target == OriginalNameTarget(OriginalNameKind.SONG, original.videoId) &&
            it.name == original.title && it.albumId != null
    } ?: return incoming
    if (englishSong.id != original.videoId || incoming.none {
            it.target == priorSong.target && it.name == priorSong.name && it.sourceVideoId == original.videoId
        }) return incoming

    // Re-use the earlier identity only to re-check its exact name in the fresh source description.
    // This is retained observed membership, not a new album identity inferred from matching text.
    val related = priorSource.filter {
        it.target.kind == OriginalNameKind.ALBUM && it.target.id == it.albumId
    }.flatMap { priorAlbum ->
        albumTrackOriginalNames(original, englishSong.copy(album = Album(priorAlbum.name, priorAlbum.target.id)))
            .filter { it.target.kind == OriginalNameKind.ALBUM && it in priorSource }
    }
    val refreshed = incoming.map { candidate ->
        when {
            candidate.target == priorSong.target && candidate.name == priorSong.name ->
                candidate.copy(albumId = priorSong.albumId)
            candidate.target.kind == OriginalNameKind.ARTIST -> priorSource.singleOrNull {
                it.target == candidate.target && it.name == candidate.name && it.albumId == priorSong.albumId
            } ?: candidate.copy(albumId = priorSong.albumId)
            else -> candidate
        }
    }
    return (refreshed + related).distinct()
}

/** One coherent source snapshot; an empty result leaves the prior snapshot untouched. */
data class OriginalSourceSnapshot(
    val names: List<ArtTrackOriginalName>,
    val incompleteMusicIdentities: Boolean,
)

/**
 * Album rows may omit their byline while proving the exact track's album membership. Reconcile
 * each kind of evidence independently instead of rejecting that membership because a previously
 * observed artist ID is absent. Retained IDs always come from this same unchanged source and
 * must be corroborated by the current complete distributor credit; no name creates a new ID.
 */
fun reconcileOriginalSourceSnapshot(
    original: ArtTrackOriginalMetadata,
    music: SongItem,
    previous: List<ArtTrackOriginalName>,
    fromAlbumPage: Boolean,
): OriginalSourceSnapshot {
    val incoming = if (fromAlbumPage) albumTrackOriginalNames(original, music) else artTrackOriginalNames(original, music)
    val prior = previous.filter { it.sourceVideoId == original.videoId }
    val artists = music.artistCredit?.artists ?: music.artists
    val priorArtists = prior.filter { it.target.kind == OriginalNameKind.ARTIST }
    val missingArtists = priorArtists.isNotEmpty() && (artists.isEmpty() || artists.any {
        ArtistIdentity.onlineId(it.id) == null || it.name.isBlank() || it.name.any { c -> c == '\n' || c == '\r' }
    })
    val missingAlbum = prior.any { it.albumId != null } && music.album?.let(::validOriginalAlbum) != true
    val incomplete = missingArtists || missingAlbum
    fun unfinished() = OriginalSourceSnapshot(emptyList(), incomplete)
    if (incoming.none { it.target == OriginalNameTarget(OriginalNameKind.SONG, original.videoId) }) return unfinished()
    val relatedProof = prior.any { it.target.kind != OriginalNameKind.SONG || it.albumId != null }
    if (!relatedProof) return OriginalSourceSnapshot(incoming, incomplete)

    val blocks = original.shortDescription.orEmpty().replace("\r\n", "\n").trim().split(Regex("\n\\s*\n"))
    val creditPrefix = original.title + " · "
    val completeDescription = blocks.size >= 4 && blocks[0].startsWith("Provided to YouTube by ") &&
        blocks[0].removePrefix("Provided to YouTube by ").isNotBlank() && blocks[1].startsWith(creditPrefix) &&
        blocks[1].removePrefix(creditPrefix).isNotBlank() && blocks[2].isNotBlank() &&
        blocks.last() == "Auto-generated by YouTube." && blocks.take(3).all { '\n' !in it && '\r' !in it }
    if (!completeDescription) return unfinished()
    val priorSong = prior.singleOrNull { it.target == OriginalNameTarget(OriginalNameKind.SONG, original.videoId) }
    // A changed title cannot join old related proof to a partial new identity observation.
    if (incomplete && priorSong?.name != original.title) return unfinished()

    val refreshed = retainCorroboratedOriginalContext(original, music, prior, incoming)
    val retainedArtists = if (missingArtists) {
        val knownIdsAgree = artists.all { artist ->
            ArtistIdentity.onlineId(artist.id)?.let { id ->
                priorArtists.any { it.target.id == id && (artist.name.isBlank() ||
                    artist.name.any { c -> c == '\n' || c == '\r' } || it.name == artist.name) }
            } ?: true
        }
        val creditMatches = exactKnownArtistCredit(blocks[1].removePrefix(creditPrefix), priorArtists.map { it.name })
            ?: return unfinished()
        if (knownIdsAgree && creditMatches) {
            val albumId = refreshed.singleOrNull { it.target.kind == OriginalNameKind.SONG }?.albumId
            priorArtists.map { it.copy(albumId = albumId ?: it.albumId) }
        } else emptyList()
    } else emptyList()
    return OriginalSourceSnapshot((refreshed + retainedArtists).distinct(), incomplete)
}

/** Match only whole, previously identified names; a delimiter inside a name is never split. */
private fun exactKnownArtistCredit(credit: String, names: List<String>): Boolean? {
    if (names.isEmpty()) return false
    if (names.size > 32) return null
    // Bound adversarial ambiguous prefixes. A failed corroboration cannot authorize an old ID.
    var remainingChecks = 4_096
    fun matches(offset: Int, remaining: List<String>): Boolean {
        if (--remainingChecks < 0) return false
        if (remaining.isEmpty()) return offset == credit.length
        return remaining.indices.any { index ->
            val token = remaining[index] + if (remaining.size == 1) "" else " · "
            credit.startsWith(token, offset) && matches(offset + token.length,
                remaining.filterIndexed { other, _ -> other != index })
        }
    }
    val result = matches(0, names)
    return if (!result && remainingChecks < 0) null else result
}

private fun validOriginalAlbum(album: Album): Boolean =
    Regex("(?:MPRE|FEmusic_library_privately_owned_release)[A-Za-z0-9_-]+").matches(album.id) &&
        album.name.isNotBlank() && album.name.none { it == '\n' || it == '\r' }

/** Raw source data survives model changes and is kept separately from the automatic assessment. */
object ArtTrackOriginalNameCodec {
    private val videoIdPattern = Regex("[A-Za-z0-9_-]{11}")
    fun encode(candidate: ArtTrackOriginalName, assessment: OriginalNameAssessment? = null): String = buildJsonObject {
        assessment?.let { value -> Json.parseToJsonElement(OriginalNameAssessmentCodec.encode(value)).jsonObject.forEach { (k, v) -> put(k, v) } }
        put("original", buildJsonObject {
            put("version", 1)
            put("kind", candidate.target.kind.name)
            put("id", candidate.target.id)
            put("name", candidate.name)
            put("sourceVideoId", candidate.sourceVideoId)
            candidate.albumId?.let { put("albumId", it) }
        })
    }.toString()

    fun decode(value: String?, target: OriginalNameTarget, name: String): ArtTrackOriginalName? =
        originalEvidenceCache.decode(value, target, name).original

    internal fun decodeRoot(root: JsonObject?, target: OriginalNameTarget, name: String): ArtTrackOriginalName? = runCatching {
        val raw = root?.get("original")?.jsonObject ?: return null
        fun text(key: String) = raw[key]?.jsonPrimitive?.takeIf { it.isString }?.content
        if (raw["version"]?.jsonPrimitive?.intOrNull != 1 || text("kind") != target.kind.name ||
            text("id") != target.id || text("name") != name || name.isBlank()) return null
        val source = text("sourceVideoId")?.takeIf { videoIdPattern.matches(it) } ?: return null
        if (target.kind == OriginalNameKind.SONG && target.id != source) return null
        val albumId = text("albumId")?.takeIf { it.isNotBlank() && it.none(Char::isWhitespace) }
        ArtTrackOriginalName(target, name, source, albumId)
    }.getOrNull()
}
