package com.dd3boh.outertune.models.metadata

import com.dd3boh.outertune.models.ArtistIdentity
import com.zionhuang.innertube.models.ArtTrackOriginalMetadata
import com.zionhuang.innertube.models.SongItem
import kotlinx.serialization.json.*

data class ArtTrackOriginalName(
    val target: OriginalNameTarget,
    val name: String,
    val sourceVideoId: String,
    val albumId: String? = null,
)

/**
 * Main's Art Track title/description carry distributor-supplied originals. The Music response
 * establishes identities; text only corroborates those existing links and never creates one.
 */
fun artTrackOriginalNames(original: ArtTrackOriginalMetadata, englishSong: SongItem): List<ArtTrackOriginalName> {
    if (original.videoId != englishSong.id || original.title.isBlank() ||
        englishSong.endpoint?.watchEndpointMusicSupportedConfigs?.watchEndpointMusicConfig?.musicVideoType != "MUSIC_VIDEO_TYPE_ATV") return emptyList()
    return buildList {
        val blocks = original.shortDescription.orEmpty().replace("\r\n", "\n").trim().split(Regex("\n\\s*\n"))
        val structured = blocks.size >= 4 && blocks.first().startsWith("Provided to YouTube by ") &&
            blocks.last() == "Auto-generated by YouTube."
        val matchingTitleCredit = structured && blocks[1].startsWith(original.title + " · ") &&
            !blocks[1].contains('\n')
        val album = englishSong.album?.takeIf {
            matchingTitleCredit && it.id.isNotBlank() && blocks[2] == it.name && !blocks[2].contains('\n')
        }
        add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.SONG, original.videoId), original.title, original.videoId, album?.id))
        // Do not parse arbitrary descriptions, Topic channel authors, music cards or free-form bios.
        if (!structured) return@buildList
        val creditedArtists = englishSong.artistCredit?.artists ?: englishSong.artists
        val linked = creditedArtists.takeIf { it.isNotEmpty() && it.all { artist -> ArtistIdentity.onlineId(artist.id) != null } }
        // Compare the entire known credit. In particular, never split a name containing a delimiter.
        if (linked != null && blocks[1] == original.title + " · " + linked.joinToString(" · ") { it.name }) {
            linked.forEach { artist ->
                add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.ARTIST, ArtistIdentity.onlineId(artist.id)!!), artist.name, original.videoId, album?.id))
            }
        }
        album?.let {
            add(ArtTrackOriginalName(OriginalNameTarget(OriginalNameKind.ALBUM, it.id), it.name, original.videoId, it.id))
        }
    }
}

/** Raw source data survives model changes and is kept separately from the automatic assessment. */
object ArtTrackOriginalNameCodec {
    fun encode(candidate: ArtTrackOriginalName, assessment: OriginalNameAssessment? = null): String = buildJsonObject {
        assessment?.let { value -> Json.parseToJsonElement(OriginalNameAssessmentCodec.encode(value)).jsonObject.forEach { (k, v) -> put(k, v) } }
        put("original", buildJsonObject {
            put("version", 1)
            put("kind", candidate.target.kind.name)
            put("id", candidate.target.id)
            put("name", candidate.name)
            put("sourceVideoId", candidate.sourceVideoId)
            candidate.albumId?.let { put("albumId", it) }
        })
    }.toString()

    fun decode(value: String?, target: OriginalNameTarget, name: String): ArtTrackOriginalName? = runCatching {
        val raw = Json.parseToJsonElement(value ?: return null).jsonObject["original"]?.jsonObject ?: return null
        fun text(key: String) = raw[key]?.jsonPrimitive?.takeIf { it.isString }?.content
        if (raw["version"]?.jsonPrimitive?.intOrNull != 1 || text("kind") != target.kind.name ||
            text("id") != target.id || text("name") != name || name.isBlank()) return null
        val source = text("sourceVideoId")?.takeIf { Regex("[A-Za-z0-9_-]{11}").matches(it) } ?: return null
        if (target.kind == OriginalNameKind.SONG && target.id != source) return null
        val albumId = text("albumId")?.takeIf { it.isNotBlank() && it.none(Char::isWhitespace) }
        ArtTrackOriginalName(target, name, source, albumId)
    }.getOrNull()
}
